version: "3.1"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-server
    environment:
      MONGO_INITDB_DATABASE: demodb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend
  backend:
    container_name: backend-project
    image: clementrb/online-wallet-backend:latest
    ports:
      - "5000:5000"
    command: sh -c "npm install && npm start"
    networks:
      - backend
  frontend:
    container_name: frontend-project
    image: clementrb/online-wallet-frontend:latest
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm rebuild node-sass && npm start "
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
